### ISSUE TITLE
--typos-delete with Tokens

### ISSUE THREAD

**Issue by GLAD22** [gurnec/btcrecover#106]
Hi,

Sorry if this is implies in the tutorial, but I wasn't clear. If I have my btcrecover-tokens-auto.txt file as the following:

se --wallet multibit-20150412201133.key --autosave progress.sav  --typos 2 --typos-capslock --typos-swap --typos-repeat --typos-delete --typos-case --typos-map typos.txt --max-typos-map 2 --typos-insert %a --max-typos-insert 2 --no-dupchecks

+ ^Did
^2^%1,4d
^3^.

I assume the resulting typos created will include instances where the full stop in 3rd token is deleted?

**Comment by gurnec** [comment]
Yes, and in your example for multiple reasons.

First, btcrecover creates passwords from the tokens in the file, and *after that* it applies one or more typos. Your file has 3 tokens. The first is required and always first, the second is optional and always second, and the third is optional and always third. That means you'll get just 3 combinations (not counting the number wildcard): `Did`, `Did%1,4d` and `Did%1,4d.`, so that's 22,221 combinations after expanding the number wildcard, about half of which don't have the optional full stop.

*After* each of these 22,221 "base" passwords are created, *then* the typos take effect. This can include up to two deletions in your example. One of those could delete the full stop *if it's even present to begin with* (half the time it won't be there). This means testing a bunch of duplicates unfortunately... for example it will test `Did1234` at least twice, once when it creates `Did1234` as a base password and doesn't apply any typo, and once where it creates `Did1234.` as a base password and then deletes the `.`. 

Hopefully this makes some sense?

**Comment by GLAD22** [comment]
That makes perfect sense, thanks very much for the thourough explanation!
