### ISSUE TITLE
Coincurve usability

### ISSUE THREAD

**Issue by ofek** [gurnec/btcrecover#127]
@gurnec I just saw https://github.com/gurnec/btcrecover/commit/f113867fa22d2f5b22175cc2b5b3892351bc1109

How are you liking Coincurve thus far? Does the API sufficiently meet your needs?

**Comment by gurnec** [comment]
Coincurve is great!

I was previously using Armory which included Python bindings to Crypto++ as its backend, and while it worked fine, Coincurve is easier to use, easier to install, and considerably faster!

There's another library out there which binds to libsecp256k1, however it's not clear that it's currently being maintained. More importantly for me is Coincurve's binary wheels (especially for Windows, where compilation can be such a pain), so many thanks for maintaining them!

As far as the API goes, since I don't use much of it, I'm a little hesitant to comment... I mostly just use PublicKey.from_valid_secret() and PublicKey.multiply(), and they suit me just fine. If something does come to mind though, I won't hesitate to comment.

Thanks!
