### ISSUE TITLE
2.147bil limit

### ISSUE THREAD

**Issue by kost123** [gurnec/btcrecover#23]
Running 1-7 lower/digit don't work because it hits the 2.147bil limit :/

**Comment by gurnec** [comment]
I'm guessing this is the same bug which @fenioh ran into and patched [here](https://github.com/fenioh/btcrecover/commit/5078856c35c26b6c42af20fa6058c37e5d8732c5). You could apply his patch (search for and change that one `sys.maxint` inside btcrecover.py to a bigger number like in the patch) or you could disable the progress bar entirely with `--no-progress`.

It's on my list to fix "properly" (not that there's anything really wrong with the patch above).

**Comment by kost123** [comment]
Can't believe you're still around, didn't expect so but cool.. okay, thanks!

**Comment by gurnec** [comment]
It's not at all a stupid question, but I'm fairly sure it wouldn't help.

MultiBit Classic .key files are so quick to check passwords against (due to Classic's lack of key stretching) that the limiting factor isn't the password-checking itself, but rather the password generation which is all written in pure Python.

The solutions for speeding this up would be to either rewrite btcrecover in a compiled language (never going to happen, sorry), write a MultiBit-checking module for some other brute-forcer such as John the Ripper, or use a faster Python interpreter such as PyPy.

PyPy seems like an easy option to try, but unfortunately it's hashing library is written in Python (unlike CPython's hashing library which is written in C), and the AES library I've chosen to work with, PyCrypto, isn't available in PyPy, thus again falling back to a pure Python version. These two factors made PyPy quite slow back when I tested it with Bitcoin Classic/Core, but I never tried it with MultiBit Classic, so maybe it would help?

If you do ever give it a try, please let me know!

**Comment by kost123** [comment]
I think I will try the JTR option, I know they have a blockchain module that I'd imagine would be helpful to look at.

**Comment by fenioh** [comment]
I just kicked the can down the road. The progress bar can handle long, but I couldnt find a "sys.maxint" equivalent.

**Comment by gurnec** [comment]
> The progress bar can handle long, but I couldnt find a "sys.maxint" equivalent.

Considering that Python's long is arbitrary-precision (limited only by available memory), I doubt you'll find one ;-)

**Comment by fenioh** [comment]
> long is arbitrary-precision

Yeah, but I hoped there is some trick to find the largest possible long for the given system.

**Comment by kost123** [comment]
Been a while but is PyCrypto still not available in pypy? I see it here: http://packages.pypy.org/

**Comment by gurnec** [comment]
It is possible to compile PyCrypto for use with PyPy. I just gave it a try and on Linux, it wasn't too difficult if you know where to find the workaround (download & extract the source, make the change [referenced here](https://bitbucket.org/pypy/compatibility/wiki/commits/c45baf75c1e15ff47080df08a1c6925cb07ecb1a#chg-Home.wiki), and compile/install with `pip install .`).

However because PyPy still implements hashlib in pure Python, it's still slower than CPython even for wallets requiring minimal hashing like MultiBit .key files. The fastest solution is to [use both](https://github.com/gurnec/btcrecover/issues/64#issuecomment-307216902) (see paragraph starting with "The second workaround").

**Comment by nori19870522** [comment]
I am Japanese and do password analysis.
https://keychainx.io/ 

This is Robert's article.
https://news.bitstarz.com/bitstarz-news-interview-robert-rhodin-keychainx-ceo  

I may be able to find the password you lost. Do you need help with your login?

**Comment by viladmir2022** [comment]
hi, if you still have wallet problem. I can recover your lost wallet.
I have powerful servers and excellent software that can find any password.
and my fee is only 15-25% of the recovered fund
here is my telegram id: @viladmir2022 and Gmail: walletsrecoveryservice@gmail.com
