### ISSUE TITLE
CAN'T GET SECOND BLOCKCHAIN PASSWORD(solved)

### ISSUE THREAD

**Issue by ajm14** [gurnec/btcrecover#248]
hello

im trying to get my second blockchain.info password

i put the command but i looks that doesnt get the pass
how can i descrypt the hash of my second password?
![second](https://user-images.githubusercontent.com/27847228/35700375-1173df44-0793-11e8-95e5-6fbfabb3a03b.png)
its the hash
YnM6PI1QsR5JxD9P7RZs7e7PsL1x9J8fvqqZNzOkKZYZqxSTC1yhNAxHuZPqq0a3KiB7iBMAABuTV7c=
can someone help me?

thanks

**Comment by ajm14** [comment]
its the hash
YnM6PI1QsR5JxD9P7RZs7e7PsL1x9J8fvqqZNzOkKZYZqxSTC1yhNAxHuZPqq0a3KiB7iBMAABuTV7c=

**Comment by crypto-recovery** [comment]
Good morning AJM,

My apologies, I'm not sure if I completely understand.  

>its the hash
YnM6PI1QsR5JxD9P7RZs7e7PsL1x9J8fvqqZNzOkKZYZqxSTC1yhNAxHuZPqq0a3KiB7iBMAABuTV7c=

Are you saying that your second blockchain.info password (the "spending" password) is the 80 character string beginning with YnM6?  If so, you appear to have done a pretty good job of choosing a hard-to-guess password. :)

In general, (and my apologies if I'm telling you something you already know), you're going to want to invoke btcrecovery with the --blockchain-secondpass command line option.

So the command line might look like:
btcrecovery.py --wallet wallet.aes.json --tokenlist tokens.txt --blockchain-secondpass

btcrecovery will then prompt you for your primary password, which you can type in and press return.

btcrecovery will then generate password variations from your tokens.txt file and test them against wallet.aes.json.

That's the introductory stuff, and it looks like you've gotten that far in the process, because the screenshot that you posted shows ptcrecovery testing 325 possible passwords.

Your next step, then, is to start iterating on either the tokens.txt file or the command line options that you submit to btcrecovery.py.

If you're confident that the spending password is closely related to the 80 character string beginning with YnM6 then I would tend to start testing with some of the --typos options that you can find here: https://github.com/gurnec/btcrecover/blob/master/TUTORIAL.md#typos

My first take would probably be to invoke btcrecovery.py like this:

btcrecovery.py --wallet wallet.aes.json --tokenlist tokens.txt --blockchain-secondpass --typos-capslock --typos-swap --typos-repeat --typos-delete --typos-case --typos 1

That will test lots of variations such as swapping characters that are next to each other, repeating characters, deleting characters, changing the case of characters and testing if CAPSLOCK was enabled.

Does that answer your question, or have I completely misunderstood and written a thousand word essay on a topic unrelated to what you wanted to know?

Thanks,
Chris

**Comment by ajm14** [comment]
Hello mate,

First of all, thanks for you help.

I've used your script, It looks that is more effective but still I cant find the password... probably has symbols like "?" "." or "%". I've used those symbols for my passwords some times so...
It's the result(i've changed " --wallet wallet.aes.json" for "--data-extract" because it didnt work):
![pass](https://user-images.githubusercontent.com/27847228/35751340-60bded72-0858-11e8-9bfb-6fd37c9a05d1.png)

thanks

**Comment by crypto-recovery** [comment]
Ah, so I did misunderstand the 80-character string you posted.  Makes sense.  I have never used the --data-extract option before.

At this point you need to start testing password variations using the tokens.txt file.

Let's suppose that your best guess is that your password is based on a couple of the following tokens:
Patriots
Eagles
2004
2018
?
%

And, let's imagine that you're sure the password contains:
- Either "Patriots" or "Eagles"  
- Followed by either "2004" or "2018"
- Followed by either "?" or "%"

You could create a tokens.txt file that contained these lines:

+ ^Patriots ^Eagles
+ ^,^2004 ^,^2018
+ ?$ %%$

And then run that with or without any of the --typos options.

At this point, now that you have btcrecovery.py running, it's just a matter of "rinse and repeat".

Thanks,
Chris

**Comment by ajm14** [comment]
thanks for you help mate!! it works
![seconddd](https://user-images.githubusercontent.com/27847228/35752431-3f60f6ac-085c-11e8-82b7-7975c988687c.png)

thanks Chris.
best regards.

**Comment by crypto-recovery** [comment]
My pleasure, glad it worked!

I would now go move your money to a new wallet immediately!

Thanks,
Chris

**Comment by ajm14** [comment]
hehe.
already is gone from blockchain.info!

thanks bro!

**Comment by crypto-recovery** [comment]
Nicely done, and congratulations!

**Comment by onoja5** [comment]
Hi, I will need help recovery my second password as well please, I have tried everything possible, but still can't, kindly help me please.

**Comment by crypto-recovery** [comment]
Good morning,

If you have specific questions about using btcrecovery.py please feel free to post them and I'll be happy to help.

If you'd rather have someone do it for you you're welcome to drop us an email at cryptoassetrecovery@gmail.com or contact us via https://cryptoassetrecovery.com/

Thanks,
Chris

**Comment by cprkrn** [comment]
I'm in the same boat as user above- have the first pass, 2fa, and second pass *hash*. 
Not sure how to decrypt the hash, tried using hashcat but says: "Separator unmatched"

Found this but at a standstill from here: https://stackoverflow.com/questions/37181281/how-do-you-keep-track-of-your-comments-in-issues-on-github

**Comment by nori19870522** [comment]
I am Japanese and do password analysis.
https://keychainx.io/ 

This is Robert's article.
https://news.bitstarz.com/bitstarz-news-interview-robert-rhodin-keychainx-ceo  

I may be able to find the password you lost. Do you need help with your login?
