### ISSUE TITLE
Can't restore previous session Error

### ISSUE THREAD

**Issue by David1931** [gurnec/btcrecover#253]
I am trying to decrypt with additional options but it gives the following error.

This is the command that I am giving.

`python btcrecover.py --wallet wallet.aes.json --tokenlist tokens.txt --typos-capslock --typos-swap --typos-repeat --typos-delete --typos-case --typos 1`

> Starting btcrecover 0.17.10 on Python 2.7.12 32-bit, 21-bit unicodes, 32-bit ints
> Read additional options from tokenlist file: --autosave progress.sav --pause --typos 1 --typos-case
> Restoring session: --autosave progress.sav --pause --typos 1 --typos-case --wallet wallet.json.aes --tokenlist tokens.txt
> Last session ended having finished password # 114
> btcrecover.py: error: can't restore previous session: the command line options have changed
> 

My tokens.txt has few non-ASCII chars like `@ # _` how do I insert the `utf-8`.
When I add `--utf8` I am getting an error `command line options have changed`

**Comment by rterwedo** [comment]
In the autosave section, it states you cannot resume a session AND change any options.  You have to keep the same options you had OR start a new session with new options.

Test a command directly on the command line (instead of in the token file).  Sort out what you want, then start an autosave session.

**Comment by David1931** [comment]
Could you let me know of how to start a new session?

**Comment by rterwedo** [comment]
@David1931 can you close this?
