### ISSUE TITLE
No extract-bitcoinj script

### ISSUE THREAD

**Issue by kost123** [gurnec/btcrecover#84]
I saw in the main code it mentions this but can't seem to find it anywhere.

**Comment by gurnec** [comment]
I never did create one, mainly because it couldn't (easily) be a stand-alone script like almost all of the other extract scripts, and partly because it would only support two wallet formats (Bitcoin for Android spending PINs and the now defunct Hive for OS X).

Do you have a need for an extract script for one of the above? Be aware that it would require installing all of btcrecover (not just the standalone script) and also [Google Protobuf](https://github.com/gurnec/btcrecover/blob/master/docs/INSTALL.md#google-protocol-buffers).

**Comment by ahmedbodi** [comment]
Could this be made?

**Comment by viladmir2022** [comment]
hi, if you still have wallet problem. I can recover your lost wallet.
I have powerful servers and excellent software that can find any password.
and my fee is only 15-25% of the recovered fund
here is my telegram id: @viladmir2022 and Gmail: walletsrecoveryservice@gmail.com
