### ISSUE TITLE
Doesn't look random enough to be a Blockchain wallet

### ISSUE THREAD

**Issue by GLAD22** [gurnec/btcrecover#94]
Hi, when I run btcrecover.py I receive an error stating that the Blockchain wallet doesn't look random enough to be encrypted as the entropy per byte is only 6.2 bits per byte. 
![image](https://user-images.githubusercontent.com/30866046/29121329-05c5474a-7d06-11e7-8d3c-657766d5276c.png)

Is there something I could possibly be doing wrong? I am running an example given in another issue discussion for my btcrecover-tokens-auto.txt file of:

#--pause --wallet multibit-20150412201133.key --autosave progress.sav --blockchain-secondpass

+ ^donkey ^Donkey

^2^%2,4[0-9]

^3^%1,2[!?]

I am trying to crack a Multibit Classic wallet, and I have my .key file in the same location as btcrecover.py.

when I try and run it from the command prompt I get the following:

![image](https://user-images.githubusercontent.com/30866046/29121395-4872556a-7d06-11e7-9af4-8c2f7dea9e1f.png)

Can anyone offer any advice?

Thanks

**Comment by gurnec** [comment]
> the Blockchain wallet doesn't look random enough to be encrypted

This is because you've told btcrecover that you're using a Blockchain.info wallet file with the `--blockchain-secondpass` option in the btcrecover-tokens-auto.txt file, and btcrecover (correctly) thinks the MultiBit .key file you provided file isn't a Blockchain.info file.

Please remove that `--blockchain-secondpass` option and try again.

Also, just as a warning, every time you change the btcrecover-tokens-auto.txt file, you'll need to delete the progress.sav file (if it's there), otherwise you'll get an error message.

**Comment by GLAD22** [comment]
Awesome, it's working now! Thanks for helping me and creating this awesome tool + write-up.
